(function(){if(!window.mightPortalUI){const s=document.createElement('script');s.src='portal-ui.js?v=1';s.async=false;document.head.appendChild(s)}const r=document.createElement('script');r.src='portal-refresh.js?v=1';r.async=false;document.head.appendChild(r)})();
const SUPABASE_URL='https://sowdiflodjxxqrarbisi.supabase.co';const SUPABASE_KEY='sb_publishable_3URkcBfqIZmtujzRnO1a1g_Xdadmjvt';const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);window.mightDb=db;const $=id=>document.getElementById(id);let otpSent=false,otpInterval=null,otpCooldown=0;
function showLogin(){if($('appView'))$('appView').classList.add('hidden');$('loginView')?.classList.remove('hidden')}
function resetOtpMode(){otpSent=false;if(otpInterval)clearInterval(otpInterval);otpInterval=null;otpCooldown=0;$('otpField')?.classList.add('hidden');$('changeEmail')?.classList.add('hidden');$('resendOtp')?.classList.add('hidden');$('otpTimer')?.classList.add('hidden');if($('otp'))$('otp').value='';if($('loginButton')){$('loginButton').disabled=false;$('loginButton').textContent='Send verification code'}if($('loginSubtitle'))$('loginSubtitle').textContent='Enter your work email to receive a secure sign-in code.';if($('loginError'))$('loginError').textContent=''}
function startCooldown(){otpCooldown=60;if(otpInterval)clearInterval(otpInterval);if($('resendOtp'))$('resendOtp').disabled=true;$('otpTimer')?.classList.remove('hidden');const tick=()=>{if(!$('otpTimer'))return;if(otpCooldown<=0){clearInterval(otpInterval);otpInterval=null;$('resendOtp')?.removeAttribute('disabled');$('otpTimer').textContent='You can request a new code now.';return}$('otpTimer').textContent=`You can request a new code in ${otpCooldown}s.`;otpCooldown--};tick();otpInterval=setInterval(tick,1000)}
function enterOtpMode(){otpSent=true;$('otpField')?.classList.remove('hidden');$('changeEmail')?.classList.remove('hidden');$('resendOtp')?.classList.remove('hidden');$('otp')?.focus();if($('loginButton'))$('loginButton').textContent='Verify code';if($('loginSubtitle'))$('loginSubtitle').textContent=`Enter the 6-digit code sent to ${$('email').value.trim().toLowerCase()}.`;startCooldown()}
async function sendOtp(){const email=$('email')?.value.trim().toLowerCase();if(!email)return;if($('loginButton'))$('loginButton').disabled=true;if($('loginError'))$('loginError').textContent='';const{error}=await db.auth.signInWithOtp({email,options:{shouldCreateUser:false}});if(error){if($('loginError'))$('loginError').textContent=error.message;if($('loginButton'))$('loginButton').disabled=false;return false}if($('loginButton'))$('loginButton').disabled=false;enterOtpMode();return true}
async function verifyOtp(){const email=$('email')?.value.trim().toLowerCase(),token=$('otp')?.value.trim();if(!/^\d{6}$/.test(token)){if($('loginError'))$('loginError').textContent='Enter the 6-digit verification code.';return false}if($('loginButton'))$('loginButton').disabled=true;if($('loginError'))$('loginError').textContent='';const{error}=await db.auth.verifyOtp({email,token,type:'email'});if(error){if($('loginError'))$('loginError').textContent='That code is invalid or expired. Please request a new code.';if($('loginButton'))$('loginButton').disabled=false;return false}return boot()}
async function signIn(e){e.preventDefault();return otpSent?verifyOtp():sendOtp()}
async function getProfile(){const{data:{user}}=await db.auth.getUser();if(!user)return null;const{data,error}=await db.from('employee_profiles').select('id,role,access_level,full_name,email,is_active').eq('id',user.id).maybeSingle();if(error)throw error;return{user,profile:data}}
async function boot(){try{const r=await getProfile();if(!r){showLogin();return false}if(!r.profile||r.profile.is_active===false){await db.auth.signOut();resetOtpMode();if($('loginError'))$('loginError').textContent='Your employee account is inactive.';showLogin();return false}const isAdmin=r.profile.role==='admin'&&r.profile.access_level==='administrator';const isDispatcher=r.profile.access_level==='dispatcher';const isBroker=r.profile.access_level==='broker'&&r.profile.role==='broker';if(!isAdmin&&!isDispatcher&&!isBroker){await db.auth.signOut();resetOtpMode();if($('loginError'))$('loginError').textContent='This account is not authorized for the operations portal.';showLogin();return false}$('userName')&&($('userName').textContent=r.profile.full_name||'Administrator');$('userEmail')&&($('userEmail').textContent=r.user.email||'');$('userAvatar')&&($('userAvatar').textContent=(r.profile.full_name||r.user.email||'A').charAt(0).toUpperCase());$('loginView')?.classList.add('hidden');$('appView')?.classList.remove('hidden');if(typeof window.mightAdminRouter?.showSection==='function'){const section=isDispatcher?'dispatch':isBroker?'quotes':((location.hash||'#dashboard').slice(1).split('/')[0]||'dashboard');await window.mightAdminRouter.showSection(section,false)}return true}catch(e){console.error(e);if($('loginError'))$('loginError').textContent='Unable to load your account. Please try again.';showLogin();return false}}
$('loginForm')?.addEventListener('submit',signIn);$('changeEmail')?.addEventListener('click',resetOtpMode);$('resendOtp')?.addEventListener('click',()=>{if(otpCooldown<=0)sendOtp()});$('otp')?.addEventListener('input',e=>{e.target.value=e.target.value.replace(/\D/g,'').slice(0,6);if(e.target.value.length===6&&!$('loginButton').disabled)verifyOtp()});$('signOut')?.addEventListener('click',async()=>{await db.auth.signOut();resetOtpMode();showLogin()});db.auth.onAuthStateChange(e=>{if(e==='SIGNED_OUT')showLogin()});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
