const SUPABASE_URL = 'https://sowdiflodjxxqrarbisi.supabase.co';
const SUPABASE_KEY = 'sb_publishable_3URkcBfqIZmtujzRnO1a1g_Xdadmjvt';
const db = supabase.createClient(SUPABASE_URL,SUPABASE_KEY); window.mightDb=db;
const $=id=>document.getElementById(id); let quotes=[],selectedQuote=null,otpSent=false,otpInterval=null,otpCooldown=0;
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
function statusLabel(v){return(v||'').replace(/_/g,' ')} function formatDate(v){if(!v)return'—';const d=new Date(String(v).length===10?v+'T00:00:00':v);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(d)} function formatQuote(n){return`ML-${String(n).padStart(5,'0')}`} function money(v){return Number(v||0).toLocaleString('en-US',{style:'currency',currency:'USD'})}
function showLogin(){$('appView').classList.add('hidden');$('loginView').classList.remove('hidden')}
function resetOtpMode(){$('otpField').classList.add('hidden');$('changeEmail').classList.add('hidden');$('resendOtp').classList.add('hidden');$('otpTimer').classList.add('hidden');$('otp').value='';$('loginButton').textContent='Send verification code';$('loginSubtitle').textContent='Enter your work email to receive a secure sign-in code.';$('loginError').textContent='';otpSent=false;if(otpInterval)clearInterval(otpInterval)}
function setOtpMode(){otpSent=true;$('otpField').classList.remove('hidden');$('changeEmail').classList.remove('hidden');$('resendOtp').classList.remove('hidden');$('otp').focus();$('loginButton').textContent='Verify code';$('loginSubtitle').textContent=`Enter the 6-digit code sent to ${$('email').value.trim()}.`;otpCooldown=60;$('resendOtp').disabled=true;$('otpTimer').classList.remove('hidden');if(otpInterval)clearInterval(otpInterval);otpInterval=setInterval(()=>{otpCooldown--;if(otpCooldown<=0){clearInterval(otpInterval);otpInterval=null;$('resendOtp').disabled=false;$('otpTimer').textContent='You can request a new code now.'}else $('otpTimer').textContent=`You can request a new code in ${otpCooldown}s.`},1000);$('otpTimer').textContent='You can request a new code in 60s.'}
async function sendOtp(){const email=$('email').value.trim().toLowerCase();$('loginError').textContent='';const{error}=await db.auth.signInWithOtp({email,options:{shouldCreateUser:false}});if(error){$('loginError').textContent=error.message;return false}setOtpMode();return true}
async function verifyOtp(){const email=$('email').value.trim().toLowerCase(),token=$('otp').value.trim();if(!/^\d{6}$/.test(token)){$('loginError').textContent='Enter the 6-digit verification code.';return}$('loginButton').disabled=true;const{error}=await db.auth.verifyOtp({email,token,type:'email'});$('loginButton').disabled=false;if(error){$('loginError').textContent='That code is invalid or expired. Please request a new code.';return}await boot()}
async function signIn(e){e.preventDefault();if(otpSent)await verifyOtp();else await sendOtp()}
async function getProfile(){const{data:{user}}=await db.auth.getUser();if(!user)return null;const{data,error}=await db.from('employee_profiles').select('id,role,full_name,is_active').eq('id',user.id).maybeSingle();if(error)throw error;return{user,profile:data}}
async function boot(){try{const r=await getProfile();if(!r){showLogin();return}if(!r.profile||r.profile.is_active===false||r.profile.role!=='admin'){await db.auth.signOut();$('loginError').textContent='Your account is not authorized for the administrator portal.';showLogin();return}$('userName').textContent=r.profile.full_name||'Administrator';$('userEmail').textContent=r.user.email||'';$('userAvatar').textContent=(r.profile.full_name||r.user.email||'A').charAt(0).toUpperCase();$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');await loadQuotes()}catch(e){console.error(e);$('loginError').textContent='Unable to load your account. Please try again.';showLogin()}}
async function loadQuotes(){if(!$('quoteRows'))return;$('quoteRows').innerHTML='<tr><td colspan="7" class="empty">Loading quote requests…</td></tr>';const{data,error}=await db.from('quote_requests').select('*').order('created_at',{ascending:false});if(error){$('quoteRows').innerHTML='<tr><td colspan="7" class="empty">Could not load quote requests.</td></tr>';return}quotes=data||[];window.quotes=quotes;renderStats();renderRows()}
function renderStats(){const c=s=>quotes.filter(q=>q.status===s).length;if($('statNew'))$('statNew').textContent=c('new');if($('statReviewing'))$('statReviewing').textContent=c('reviewing');if($('statQuoting'))$('statQuoting').textContent=c('quoting');if($('statBooked'))$('statBooked').textContent=c('booked')}
function renderRows(){if(!$('search')||!$('quoteRows'))return;const t=$('search').value.trim().toLowerCase(),f=$('statusFilter').value,a=quotes.filter(q=>(f==='all'||q.status===f)&&(!t||[formatQuote(q.quote_number),q.company_name,q.customer_name,q.origin,q.destination,q.equipment,q.email].some(v=>String(v||'').toLowerCase().includes(t))));if(!a.length){$('quoteRows').innerHTML='<tr><td colspan="7" class="empty">No quote requests match your filters.</td></tr>';return}$('quoteRows').innerHTML=a.map(q=>`<tr><td>${formatQuote(q.quote_number)}</td><td><strong>${esc(q.company_name)}</strong><span>${esc(q.customer_name)}</span></td><td>${esc(q.origin)} → ${esc(q.destination)}</td><td>${esc(q.equipment)}</td><td>${formatDate(q.pickup_date)}</td><td><span class="status ${esc(q.status)}">${esc(statusLabel(q.status))}</span></td><td><button class="outline open-quote" data-id="${q.id}">View</button></td></tr>`).join('');document.querySelectorAll('.open-quote').forEach(b=>b.addEventListener('click',()=>openQuote(b.dataset.id)))}
function openQuote(id){selectedQuote=quotes.find(q=>q.id===id);if(!selectedQuote)return;if($('drawerTitle'))$('drawerTitle').textContent=formatQuote(selectedQuote.quote_number);if($('detailStatus'))$('detailStatus').value=selectedQuote.status||'new';if($('internalNotes'))$('internalNotes').value=selectedQuote.internal_notes||'';if($('carrierRate'))$('carrierRate').value=selectedQuote.carrier_rate??'';if($('customerRate'))$('customerRate').value=selectedQuote.customer_rate??'';if($('drawerBody'))$('drawerBody').innerHTML=`<div class="detail-grid"><div><b>Company</b><p>${esc(selectedQuote.company_name)}</p></div><div><b>Contact</b><p>${esc(selectedQuote.customer_name)}</p></div><div><b>Email</b><p>${esc(selectedQuote.email)}</p></div><div><b>Phone</b><p>${esc(selectedQuote.phone)}</p></div><div><b>Origin</b><p>${esc(selectedQuote.origin)}</p></div><div><b>Destination</b><p>${esc(selectedQuote.destination)}</p></div><div><b>Pickup</b><p>${formatDate(selectedQuote.pickup_date)}</p></div><div><b>Equipment</b><p>${esc(selectedQuote.equipment)}</p></div></div>`;$('drawer')?.classList.remove('hidden')}
async function saveQuote(){if(!selectedQuote)return;const carrier=Number($('carrierRate').value||0),customer=Number($('customerRate').value||0);const{error}=await db.from('quote_requests').update({status:$('detailStatus').value,carrier_rate:carrier||null,customer_rate:customer||null,margin:(customer-carrier)||null,internal_notes:$('internalNotes').value.trim(),updated_at:new Date().toISOString()}).eq('id',selectedQuote.id);if(error){$('saveMessage').textContent='Could not save changes.';return}$('saveMessage').textContent='Saved.';await loadQuotes()}
$('loginForm')?.addEventListener('submit',signIn);$('changeEmail')?.addEventListener('click',resetOtpMode);$('resendOtp')?.addEventListener('click',sendOtp);$('otp')?.addEventListener('input',e=>e.target.value=e.target.value.replace(/\D/g,'').slice(0,6));$('signOut')?.addEventListener('click',async()=>{await db.auth.signOut();resetOtpMode();showLogin()});$('refresh')?.addEventListener('click',loadQuotes);$('search')?.addEventListener('input',renderRows);$('statusFilter')?.addEventListener('change',renderRows);$('drawerClose')?.addEventListener('click',()=>$('drawer').classList.add('hidden'));$('drawerX')?.addEventListener('click',()=>$('drawer').classList.add('hidden'));$('saveQuote')?.addEventListener('click',saveQuote);db.auth.onAuthStateChange(e=>{if(e==='SIGNED_OUT')showLogin()});boot();