(function(){
  if(window.mightAttendanceGateLoaded)return;window.mightAttendanceGateLoaded=true;
  const db=window.mightDb;let profile=null,record=null;
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  function workDate(){const zone=profile?.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC';return new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
  function ensureStyle(){if(document.getElementById('attendanceGateStyle'))return;const s=document.createElement('style');s.id='attendanceGateStyle';s.textContent=`#attendanceGateBar{position:fixed;right:24px;bottom:24px;z-index:9500;background:#102f48;color:#fff;border-radius:12px;padding:10px 12px;box-shadow:0 12px 35px #0003;display:flex;align-items:center;gap:12px;font:600 13px Inter,sans-serif}#attendanceGateBar button{border:0;border-radius:8px;padding:9px 13px;background:#176fbe;color:#fff;font:800 12px Inter,sans-serif;cursor:pointer}#attendanceGateBar .clock{font-variant-numeric:tabular-nums;color:#dce9f4}#attendanceGate{position:fixed;inset:0;z-index:12000;background:#061522ee;display:flex;align-items:center;justify-content:center;padding:20px}#attendanceGate.hidden{display:none}#attendanceGate .card{width:min(520px,100%);background:#fff;border-radius:18px;padding:34px;box-shadow:0 30px 90px #0005;text-align:center}#attendanceGate .mark{width:52px;height:52px;border-radius:14px;background:#092239;color:#fff;display:grid;place-items:center;font:900 24px Inter,sans-serif;margin:0 auto 18px}#attendanceGate h2{margin:0;color:#081a2b;font:800 27px Inter,sans-serif}#attendanceGate p{color:#6d8195;line-height:1.6;margin:10px 0 22px}#attendanceGate .schedule{background:#f4f7fa;border:1px solid #dbe4ec;border-radius:10px;padding:12px;margin-bottom:18px;color:#50677b;font-size:13px}#attendanceGate button{width:100%;border:0;border-radius:9px;background:#176fbe;color:#fff;padding:13px;font:800 14px Inter,sans-serif;cursor:pointer}#attendanceGate .error{color:#a23a35;margin-top:10px;font-size:12px}`;document.head.appendChild(s)}
  function removeGate(){document.getElementById('attendanceGate')?.remove()}
  function showGate(){ensureStyle();if(document.getElementById('attendanceGate'))return;const m=document.createElement('div');m.id='attendanceGate';m.innerHTML=`<div class="card"><div class="mark">M</div><div style="font-size:10px;letter-spacing:.16em;font-weight:800;color:#176fbe;margin-bottom:7px">MIGHT LOGISTICS</div><h2>Good morning, ${esc(profile?.full_name?.split(' ')[0]||'there')}.</h2><p>You are signed in, but you have not checked in for today's shift yet. Check in before starting work so your attendance is recorded.</p><div class="schedule">Scheduled shift: <strong>${esc(profile?.scheduled_start_time?.slice(0,5)||'Not set')} – ${esc(profile?.scheduled_end_time?.slice(0,5)||'Not set')}</strong></div><button id="attendanceCheckIn">Check in & start work</button><div class="error" id="attendanceGateError"></div></div>`;document.body.appendChild(m);m.querySelector('#attendanceCheckIn').onclick=checkIn}
  function showBar(){ensureStyle();let b=document.getElementById('attendanceGateBar');if(!b){b=document.createElement('div');b.id='attendanceGateBar';document.body.appendChild(b)}const checked=!!record?.check_in_at;const label=checked&&!record?.check_out_at?'Checked in':'Not checked in';b.innerHTML=`<span>${esc(profile?.employee_code||'')} · ${label}</span><span class="clock" id="attendanceClock"></span>${checked&&!record?.check_out_at?'<button id="attendanceCheckOut">Check out</button>':''}`;if(checked&&!record?.check_out_at)b.querySelector('#attendanceCheckOut').onclick=checkOut;const tick=()=>{const c=document.getElementById('attendanceClock');if(c)c.textContent=new Date().toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',second:'2-digit'})};tick();clearInterval(b._clock);b._clock=setInterval(tick,1000)}
  async function loadRecord(){const d=workDate();const r=await db.from('employee_attendance').select('*').eq('employee_id',profile.id).eq('work_date',d).maybeSingle();if(r.error)throw r.error;record=r.data||null}
  async function checkIn(){const err=document.getElementById('attendanceGateError');try{const now=new Date().toISOString();const d=workDate();const r=await db.from('employee_attendance').upsert({employee_id:profile.id,work_date:d,check_in_at:now,status:'open'},{onConflict:'employee_id,work_date'}).select().single();if(r.error)throw r.error;record=r.data;removeGate();showBar()}catch(e){if(err)err.textContent=e.message||'Could not record check-in.'}}
  async function checkOut(){if(!record)return;try{const r=await db.from('employee_attendance').update({check_out_at:new Date().toISOString(),status:'completed',updated_at:new Date().toISOString()}).eq('id',record.id).select().single();if(r.error)throw r.error;record=r.data;showBar()}catch(e){alert(e.message||'Could not record check-out.')}}
  async function init(){try{const {data:{user}}=await db.auth.getUser();if(!user)return;const r=await db.from('employee_profiles').select('*').eq('id',user.id).maybeSingle();if(r.error||!r.data||r.data.is_active===false)return;profile=r.data;if(profile.role==='admin'&&profile.access_level==='administrator')return;await loadRecord();showBar();if(!record?.check_in_at)showGate()}catch(e){console.error('Attendance gate failed',e)}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,700));else setTimeout(init,700);
  window.mightAttendanceGate={init,checkIn,checkOut};
})();