(function(){
  if(window.mightBrokerageAdminLoaded)return; window.mightBrokerageAdminLoaded=true;
  const db=()=>window.mightDb;
  const money=v=>Number(v||0).toLocaleString('en-US',{style:'currency',currency:'USD'});
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const q=s=>document.querySelector(s);
  function addSections(){
    const main=q('main.main'); if(!main)return;
    if(!q('#documents')){const s=document.createElement('section');s.className='content hidden';s.id='documents';s.innerHTML=`<section class="panel"><div class="panel-head"><div><div class="kicker">LOAD DOCUMENTS</div><h3>Documents</h3><p class="panel-subtitle">Rate confirmations, BOLs, PODs, invoices and other paperwork attached to brokerage loads.</p></div><div class="controls"><select id="docLoad"><option value="">All loads</option></select><select id="docType"><option value="">All types</option><option>Rate Confirmation</option><option>BOL</option><option>POD</option><option>Invoice</option><option>Carrier Paperwork</option><option>Other</option></select><input id="docFile" type="file"><button id="docUpload" class="primary">Upload Document</button></div></div><div class="table-wrap"><table><thead><tr><th>Load</th><th>Document</th><th>Type</th><th>Uploaded</th><th>Size</th><th></th></tr></thead><tbody id="docRows"><tr><td colspan="6" class="empty">Loading documents…</td></tr></tbody></table></div></section>`;main.appendChild(s)}
    if(!q('#billing')){const s=document.createElement('section');s.className='content hidden';s.id='billing';s.innerHTML=`<section class="panel"><div class="panel-head"><div><div class="kicker">FINANCE</div><h3>Billing</h3><p class="panel-subtitle">Track customer receivables and carrier payables separately.</p></div><div class="controls"><select id="billingPeriod"><option value="this_month">This month</option><option value="last_month">Last month</option><option value="this_quarter">This quarter</option><option value="last_6">Last 6 months</option><option value="this_year">This year</option><option value="last_year">Last year</option></select><button id="newInvoice" class="primary">+ Customer Invoice</button><button id="newPayable" class="outline">+ Carrier Payable</button></div></div><div class="stats" id="billingStats"><div class="stat"><span>INVOICED</span><strong id="billInvoiced">$0</strong><small>Customer invoices</small></div><div class="stat"><span>AR OUTSTANDING</span><strong id="billAR">$0</strong><small>Unpaid customer balance</small></div><div class="stat"><span>AP OUTSTANDING</span><strong id="billAP">$0</strong><small>Unpaid carrier balance</small></div><div class="stat"><span>PAID</span><strong id="billPaid">$0</strong><small>Collected from customers</small></div></div><div class="panel" style="margin-top:16px"><div class="panel-head"><div><div class="kicker">ACCOUNTS RECEIVABLE</div><h3>Customer Invoices</h3></div></div><div class="table-wrap"><table><thead><tr><th>Invoice</th><th>Customer</th><th>Load</th><th>Issue</th><th>Due</th><th>Amount</th><th>Paid</th><th>Status</th></tr></thead><tbody id="invoiceRows"><tr><td colspan="8" class="empty">Loading invoices…</td></tr></tbody></table></div></div><div class="panel" style="margin-top:16px"><div class="panel-head"><div><div class="kicker">ACCOUNTS PAYABLE</div><h3>Carrier Payables</h3></div></div><div class="table-wrap"><table><thead><tr><th>Payable</th><th>Carrier</th><th>Load</th><th>Issue</th><th>Due</th><th>Amount</th><th>Paid</th><th>Status</th></tr></thead><tbody id="payableRows"><tr><td colspan="8" class="empty">Loading payables…</td></tr></tbody></table></div></div></section>`;main.appendChild(s)}
    if(!q('#reports')){const s=document.createElement('section');s.className='content hidden';s.id='reports';s.innerHTML=`<section class="panel"><div class="panel-head"><div><div class="kicker">ANALYTICS</div><h3>Brokerage Reports</h3><p class="panel-subtitle">Live operational and financial reporting from brokerage loads and billing.</p></div><div class="controls"><select id="reportPeriod"><option value="this_month">This month</option><option value="last_month">Last month</option><option value="this_quarter">This quarter</option><option value="last_6">Last 6 months</option><option value="this_year">This year</option><option value="last_year">Last year</option></select><button id="reportRefresh" class="outline">Refresh</button></div></div><div class="stats"><div class="stat"><span>REVENUE</span><strong id="repRevenue">$0</strong><small>Customer-rate value</small></div><div class="stat"><span>GROSS PROFIT</span><strong id="repProfit">$0</strong><small>Customer rate less carrier rate</small></div><div class="stat"><span>MARGIN</span><strong id="repMargin">0.0%</strong><small>Blended load margin</small></div><div class="stat"><span>LOADS</span><strong id="repLoads">0</strong><small>Loads created in period</small></div></div><div class="panel" style="margin-top:16px"><div class="panel-head"><div><div class="kicker">PERFORMANCE</div><h3>Customer Performance</h3></div></div><div class="table-wrap"><table><thead><tr><th>Customer</th><th>Loads</th><th>Revenue</th><th>Gross Profit</th><th>Margin</th></tr></thead><tbody id="repCustomerRows"><tr><td colspan="5" class="empty">Loading report…</td></tr></tbody></table></div></div></section>`;main.appendChild(s)}
  }
  function nav(){
    const n=q('aside.sidebar nav'); if(!n)return;
    const items=[['documents','Documents'],['billing','Billing'],['reports','Reports']];
    items.forEach(([id,label])=>{if(!n.querySelector(`[data-section="${id}"]`)){const a=document.createElement('a');a.href='#'+id;a.dataset.section=id;a.textContent=label;n.appendChild(a)}});
  }
  function range(key){const d=new Date(),y=d.getFullYear(),m=d.getMonth();let start,end;
    if(key==='last_month'){start=new Date(y,m-1,1);end=new Date(y,m,1)} else if(key==='this_quarter'){const q=Math.floor(m/3)*3;start=new Date(y,q,1);end=new Date(y,q+3,1)} else if(key==='last_6'){start=new Date(y,m-5,1);end=new Date(y,m+1,1)} else if(key==='this_year'){start=new Date(y,0,1);end=new Date(y+1,0,1)} else if(key==='last_year'){start=new Date(y-1,0,1);end=new Date(y,0,1)} else {start=new Date(y,m,1);end=new Date(y,m+1,1)} return {start,end};}
  async function loads(){const d=db();if(!d)return[];const {data}=await d.from('loads').select('id,load_number,origin,destination,customer_rate,carrier_rate,created_at,customer_id').eq('is_hidden',false).order('created_at',{ascending:false});return data||[]}
  async function loadDocData(){const d=db();if(!d)return;const [docs,ls]=await Promise.all([d.from('load_documents').select('id,load_id,document_type,file_name,mime_type,file_size,storage_path,created_at').order('created_at',{ascending:false}),loads()]);
    const lm=new Map(ls.map(x=>[x.id,x]));const loadSel=q('#docLoad');if(loadSel)loadSel.innerHTML='<option value="">All loads</option>'+ls.map(x=>`<option value="${x.id}">${esc(x.load_number)} — ${esc(x.origin)} → ${esc(x.destination)}</option>`).join('');
    renderDocs(docs.data||[]);
  }
  function renderDocs(rows){const selected=q('#docLoad')?.value||'',type=q('#docType')?.value||'';const data=rows.filter(x=>(!selected||x.load_id===selected)&&(!type||x.document_type===type));const lsCache=window._brokerageLoads||[];const lm=new Map(lsCache.map(x=>[x.id,x]));const el=q('#docRows');if(!el)return;el.innerHTML=data.map(x=>{const l=lm.get(x.load_id);return `<tr><td>${esc(l?.load_number||x.load_id)}</td><td>${esc(x.file_name)}</td><td>${esc(x.document_type)}</td><td>${new Date(x.created_at).toLocaleString()}</td><td>${x.file_size?Math.round(x.file_size/1024)+' KB':'—'}</td><td>${x.storage_path?`<button class="outline doc-download" data-path="${esc(x.storage_path)}">View</button>`:'—'}</td></tr>`}).join('')||'<tr><td colspan="6" class="empty">No documents found.</td></tr>';}
  async function initDocs(){window._brokerageLoads=await loads();await loadDocData();q('#docLoad')?.addEventListener('change',loadDocData);q('#docType')?.addEventListener('change',loadDocData);q('#docUpload')?.addEventListener('click',uploadDoc);}
  async function uploadDoc(){const d=db(),file=q('#docFile')?.files?.[0],loadId=q('#docLoad')?.value,type=q('#docType')?.value||'Other';if(!d||!file||!loadId){alert('Select a load, document type, and file.');return}const path=`${loadId}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await d.storage.from('load-documents').upload(path,file,{upsert:false});if(up.error){alert(up.error.message);return}const ins=await d.from('load_documents').insert({load_id:loadId,document_type:type,file_name:file.name,mime_type:file.type,file_size:file.size,storage_path:path,created_by:(await d.auth.getUser()).data.user?.id});if(ins.error){await d.storage.from('load-documents').remove([path]);alert(ins.error.message);return}q('#docFile').value='';await initDocs();}
  async function billing(){const d=db();if(!d)return;const [inv,pay]=await Promise.all([d.from('customer_invoices').select('*,customers(company_name),loads(load_number)').order('issue_date',{ascending:false}),d.from('carrier_payables').select('*,carriers(legal_name),loads(load_number)').order('issue_date',{ascending:false})]);const ir=inv.data||[],pr=pay.data||[];q('#invoiceRows').innerHTML=ir.map(x=>`<tr><td>${esc(x.invoice_number)}</td><td>${esc(x.customers?.company_name||'—')}</td><td>${esc(x.loads?.load_number||'—')}</td><td>${esc(x.issue_date)}</td><td>${esc(x.due_date||'—')}</td><td>${money(x.subtotal)}</td><td>${money(x.amount_paid)}</td><td>${esc(x.status)}</td></tr>`).join('')||'<tr><td colspan="8" class="empty">No customer invoices yet.</td></tr>';q('#payableRows').innerHTML=pr.map(x=>`<tr><td>${esc(x.payable_number)}</td><td>${esc(x.carriers?.legal_name||'—')}</td><td>${esc(x.loads?.load_number||'—')}</td><td>${esc(x.issue_date)}</td><td>${esc(x.due_date||'—')}</td><td>${money(x.amount)}</td><td>${money(x.amount_paid)}</td><td>${esc(x.status)}</td></tr>`).join('')||'<tr><td colspan="8" class="empty">No carrier payables yet.</td></tr>';const invoiced=ir.reduce((a,x)=>a+Number(x.subtotal||0),0),ar=ir.reduce((a,x)=>a+Math.max(0,Number(x.subtotal||0)-Number(x.amount_paid||0)),0),ap=pr.reduce((a,x)=>a+Math.max(0,Number(x.amount||0)-Number(x.amount_paid||0)),0),paid=ir.reduce((a,x)=>a+Number(x.amount_paid||0),0);q('#billInvoiced').textContent=money(invoiced);q('#billAR').textContent=money(ar);q('#billAP').textContent=money(ap);q('#billPaid').textContent=money(paid);}
  async function reports(){const d=db();if(!d)return;const r=range(q('#reportPeriod')?.value||'this_month');const {data}=await d.from('loads').select('id,customer_id,customer_rate,carrier_rate,customer_id,customers(company_name)').eq('is_hidden',false).gte('created_at',r.start.toISOString()).lt('created_at',r.end.toISOString());const rows=data||[];const revenue=rows.reduce((a,x)=>a+Number(x.customer_rate||0),0),profit=rows.reduce((a,x)=>a+Number(x.customer_rate||0)-Number(x.carrier_rate||0),0);q('#repRevenue').textContent=money(revenue);q('#repProfit').textContent=money(profit);q('#repMargin').textContent=(revenue?profit/revenue*100:0).toFixed(1)+'%';q('#repLoads').textContent=rows.length;const map={};rows.forEach(x=>{const n=x.customers?.company_name||'Unassigned';map[n]??={loads:0,revenue:0,profit:0};map[n].loads++;map[n].revenue+=Number(x.customer_rate||0);map[n].profit+=Number(x.customer_rate||0)-Number(x.carrier_rate||0)});q('#repCustomerRows').innerHTML=Object.entries(map).sort((a,b)=>b[1].revenue-a[1].revenue).map(([n,v])=>`<tr><td>${esc(n)}</td><td>${v.loads}</td><td>${money(v.revenue)}</td><td>${money(v.profit)}</td><td>${(v.revenue?v.profit/v.revenue*100:0).toFixed(1)}%</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No loads in this period.</td></tr>';}
  function invoiceForm(){const box=document.createElement('div');box.className='drawer';box.innerHTML=`<div class="drawer-backdrop"></div><aside class="drawer-panel"><div class="drawer-head"><div><div class="kicker">ACCOUNTS RECEIVABLE</div><h3>New Customer Invoice</h3></div><button class="close">×</button></div><form class="drawer-body" id="newInvoiceForm"><label>Invoice Number<input name="invoice_number" required placeholder="INV-10001"></label><label>Customer ID<input name="customer_id" placeholder="Customer UUID"></label><label>Load ID<input name="load_id" placeholder="Load UUID"></label><label>Issue Date<input name="issue_date" type="date"></label><label>Due Date<input name="due_date" type="date"></label><label>Amount<input name="subtotal" type="number" step="0.01" required></label><label>Notes<textarea name="notes"></textarea></label><button class="primary" type="submit">Create Invoice</button></form></aside></div>`;document.body.appendChild(box);box.classList.remove('hidden');box.querySelector('.close').onclick=()=>box.remove();box.querySelector('.drawer-backdrop').onclick=()=>box.remove();box.querySelector('form').onsubmit=async e=>{e.preventDefault();const d=db(),f=new FormData(e.target),u=(await d.auth.getUser()).data.user;const payload=Object.fromEntries(f.entries());payload.created_by=u?.id||null;payload.issue_date=payload.issue_date||new Date().toISOString().slice(0,10);payload.customer_id=payload.customer_id||null;payload.load_id=payload.load_id||null;const {error}=await d.from('customer_invoices').insert(payload);if(error)alert(error.message);else{box.remove();billing()}};}
  function wire(){q('#newInvoice')?.addEventListener('click',invoiceForm);q('#billingPeriod')?.addEventListener('change',billing);q('#reportPeriod')?.addEventListener('change',reports);q('#reportRefresh')?.addEventListener('click',reports);}
  async function init(){addSections();nav();wire();await initDocs();await billing();await reports();}
  window.initMightBrokerageAdmin=init;window.refreshMightBrokerage=init;
})();