(function(){
  if(window.mightDispatchLoaded)return; window.mightDispatchLoaded=true;
  const db=window.mightDb;
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const money=v=>Number(v||0).toLocaleString('en-US',{style:'currency',currency:'USD'});
  const date=v=>v?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date(v+'T00:00:00')):'—';
  let profile=null, clients=[], trucks=[], dispatchers=[], assignments=[], loads=[];

  function addNav(){
    const nav=document.querySelector('aside.sidebar nav'); if(!nav||nav.querySelector('[data-section="dispatch"]'))return;
    const a=document.createElement('a'); a.href='#dispatch'; a.dataset.section='dispatch'; a.textContent='Dispatch';
    nav.appendChild(a);
  }

  function addStyles(){if($('dispatchStyles'))return;const s=document.createElement('style');s.id='dispatchStyles';s.textContent=`
    #dispatch .dispatch-toolbar{display:flex;gap:10px;flex-wrap:wrap;align-items:center}
    #dispatch .dispatch-tabs{display:flex;gap:8px;margin-bottom:18px;flex-wrap:wrap}
    #dispatch .dispatch-tab{border:1px solid #d9e2ec;background:#fff;color:#0d2338;padding:9px 14px;border-radius:10px;font-weight:700;cursor:pointer}
    #dispatch .dispatch-tab.active{background:#176fbe;color:#fff;border-color:#176fbe;box-shadow:0 8px 20px rgba(23,111,190,.18)}
    #dispatch .dispatch-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin-bottom:18px}
    #dispatch .dispatch-kpi{background:#fff;border:1px solid #e2e8ef;border-radius:14px;padding:18px;box-shadow:0 8px 24px rgba(13,35,56,.05)}
    #dispatch .dispatch-kpi span{display:block;color:#66768a;font-size:11px;font-weight:800;letter-spacing:.08em}.dispatch-kpi strong{display:block;font-size:28px;margin:6px 0;color:#0d2338}.dispatch-kpi small{color:#718096}
    #dispatch .dispatch-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}
    #dispatch .dispatch-table td{vertical-align:middle}.dispatch-badge{display:inline-flex;padding:5px 9px;border-radius:999px;background:#eef5fb;color:#176fbe;font-size:11px;font-weight:800;text-transform:capitalize}.dispatch-badge.green{background:#eaf8f2;color:#18845a}.dispatch-badge.amber{background:#fff5e7;color:#a86b0b}
    #dispatch .dispatch-modal{position:fixed;inset:0;z-index:1000;display:flex;align-items:center;justify-content:center;padding:24px}.dispatch-modal.hidden{display:none}.dispatch-backdrop{position:absolute;inset:0;background:rgba(13,35,56,.5);backdrop-filter:blur(4px)}.dispatch-dialog{position:relative;background:#fff;border-radius:18px;width:min(900px,100%);max-height:90vh;overflow:auto;box-shadow:0 30px 80px rgba(13,35,56,.25);padding:24px}.dispatch-dialog h3{margin:0}.dispatch-form{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:18px}.dispatch-form label{display:flex;flex-direction:column;gap:6px;font-size:12px;font-weight:800;color:#526174}.dispatch-form .full{grid-column:1/-1}.dispatch-form input,.dispatch-form select,.dispatch-form textarea{padding:11px 12px;border:1px solid #d8e1ea;border-radius:9px;font:inherit}.dispatch-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:20px}.dispatch-close{position:absolute;right:18px;top:15px;border:0;background:none;font-size:28px;color:#718096;cursor:pointer}
    @media(max-width:900px){#dispatch .dispatch-kpis{grid-template-columns:repeat(2,1fr)}#dispatch .dispatch-grid{grid-template-columns:1fr}.dispatch-form{grid-template-columns:1fr}}
  `;document.head.appendChild(s)}

  function buildSection(){
    if($('dispatch'))return;
    const main=document.querySelector('main.main'); if(!main)return;
    const sec=document.createElement('section'); sec.className='content hidden'; sec.id='dispatch';
    sec.innerHTML=`<div class="panel-head"><div><div class="kicker">DISPATCH OPERATIONS</div><h3>Dispatch Management</h3><p class="panel-subtitle">Manage dispatch clients, fleets, dispatcher assignments, and accepted loads.</p></div><div class="dispatch-toolbar"><select id="dispatchPeriod"><option value="month">This Month</option><option value="last_month">Last Month</option><option value="quarter">This Quarter</option><option value="six">Last 6 Months</option><option value="year">This Year</option><option value="last_year">Last Year</option></select><button id="dispatchRefresh" class="outline">Refresh</button><button id="newDispatchClient" class="primary">+ Dispatch Client</button><button id="newDispatchLoad" class="primary">+ Accepted Load</button></div></div>
      <div class="dispatch-kpis"><div class="dispatch-kpi"><span>ACTIVE CLIENTS</span><strong id="dKpiClients">—</strong><small>Current dispatch accounts</small></div><div class="dispatch-kpi"><span>ACTIVE TRUCKS</span><strong id="dKpiTrucks">—</strong><small>Fleet under dispatch</small></div><div class="dispatch-kpi"><span>ACCEPTED LOADS</span><strong id="dKpiLoads">—</strong><small>In selected period</small></div><div class="dispatch-kpi"><span>DISPATCH REVENUE</span><strong id="dKpiRevenue">—</strong><small>Fees generated</small></div></div>
      <div class="dispatch-tabs"><button class="dispatch-tab active" data-tab="clients">Clients & Fleet</button><button class="dispatch-tab" data-tab="loads">Accepted Loads</button><button class="dispatch-tab" data-tab="dispatchers">Dispatchers</button></div>
      <div id="dispatchClientsTab"><section class="panel"><div class="panel-head"><div><div class="kicker">CLIENT FLEET</div><h3>Dispatch Clients</h3></div><input id="dispatchClientSearch" type="search" placeholder="Search company, MC, DOT"></div><div class="table-wrap"><table class="dispatch-table"><thead><tr><th>Client</th><th>MC</th><th>Plan</th><th>Trucks</th><th>Dispatcher</th><th>Status</th><th></th></tr></thead><tbody id="dispatchClientRows"><tr><td colspan="7" class="empty">Loading…</td></tr></tbody></table></div></section></div>
      <div id="dispatchLoadsTab" class="hidden"><section class="panel"><div class="panel-head"><div><div class="kicker">ACCEPTED LOADS</div><h3>Dispatch Loads</h3></div><div class="controls"><input id="dispatchLoadSearch" type="search" placeholder="Search load, lane, broker"><select id="dispatchLoadStatus"><option value="all">All statuses</option><option value="accepted">Accepted</option><option value="booked">Booked</option><option value="picked_up">Picked Up</option><option value="in_transit">In Transit</option><option value="delivered">Delivered</option><option value="invoiced">Invoiced</option><option value="paid">Paid</option></select></div></div><div class="table-wrap"><table class="dispatch-table"><thead><tr><th>Load</th><th>Client / Truck</th><th>Lane</th><th>Rate</th><th>Dispatch Fee</th><th>Dispatcher</th><th>Status</th></tr></thead><tbody id="dispatchLoadRows"><tr><td colspan="7" class="empty">Loading…</td></tr></tbody></table></div></section></div>
      <div id="dispatchersTab" class="hidden"><section class="panel"><div class="panel-head"><div><div class="kicker">TEAM</div><h3>Dispatchers</h3></div><button id="newDispatcher" class="primary">+ Create Dispatcher</button></div><div class="table-wrap"><table class="dispatch-table"><thead><tr><th>Dispatcher</th><th>Email</th><th>Assigned Trucks</th><th>Capacity</th><th>Status</th></tr></thead><tbody id="dispatcherRows"><tr><td colspan="5" class="empty">Loading…</td></tr></tbody></table></div></section></div>`;
    main.appendChild(sec);
    addStyles(); addNav(); bind();
  }

  function periodStart(key){const now=new Date();let s=new Date(now.getFullYear(),now.getMonth(),1);if(key==='last_month')s=new Date(now.getFullYear(),now.getMonth()-1,1);if(key==='quarter'){const q=Math.floor(now.getMonth()/3)*3;s=new Date(now.getFullYear(),q,1)}if(key==='six')s=new Date(now.getFullYear(),now.getMonth()-5,1);if(key==='year')s=new Date(now.getFullYear(),0,1);if(key==='last_year')s=new Date(now.getFullYear()-1,0,1);return s.toISOString().slice(0,10)}

  async function loadAll(){
    if(!profile)return;
    const assigned=profile.access_level==='dispatcher';
    let cq=db.from('dispatch_clients').select('*').order('company_name');
    let tq=db.from('dispatch_trucks').select('*').order('unit_number');
    let aq=db.from('dispatch_client_dispatchers').select('*');
    let dq=db.from('employee_profiles').select('id,full_name,email,is_active,access_level').eq('access_level','dispatcher').order('full_name');
    let lq=db.from('dispatch_loads').select('*').order('accepted_at',{ascending:false});
    const [c,t,a,d,l]=await Promise.all([cq,tq,aq,dq,lq]);
    for(const x of [c,t,a,d,l])if(x.error)throw x.error;
    clients=c.data||[];trucks=t.data||[];assignments=a.data||[];dispatchers=d.data||[];loads=l.data||[];
    render();
  }
  function filteredLoads(){const p=$('dispatchPeriod')?.value||'month';const start=periodStart(p);return loads.filter(l=>(l.accepted_at||l.created_at||'')>=start)}
  function render(){
    const ls=filteredLoads();const activeClients=clients.filter(c=>c.status==='active');const activeTrucks=trucks.filter(t=>t.status==='active');$('dKpiClients').textContent=activeClients.length;$('dKpiTrucks').textContent=activeTrucks.length;$('dKpiLoads').textContent=ls.length;$('dKpiRevenue').textContent=money(ls.reduce((s,l)=>s+Number(l.dispatch_fee||0),0));
    const term=($('dispatchClientSearch')?.value||'').toLowerCase();$('dispatchClientRows').innerHTML=clients.filter(c=>[c.company_name,c.mc_number,c.dot_number].join(' ').toLowerCase().includes(term)).map(c=>{const ts=trucks.filter(t=>t.client_id===c.id);const as=assignments.filter(a=>a.client_id===c.id&&a.active);const names=as.map(a=>dispatchers.find(d=>d.id===a.dispatcher_id)?.full_name).filter(Boolean).join(', ')||'Unassigned';return `<tr><td><strong>${esc(c.company_name)}</strong><small>${esc(c.contact_name||'')}</small></td><td>${esc(c.mc_number||'—')}</td><td>${esc(c.fee_type||'—')} ${c.fee_value?esc(c.fee_value):''}</td><td>${ts.length}</td><td>${esc(names)}</td><td><span class="dispatch-badge ${c.status==='active'?'green':'amber'}">${esc(c.status||'')}</span></td><td><button class="outline dispatch-client-view" data-id="${c.id}">Manage Fleet</button></td></tr>`}).join('')||'<tr><td colspan="7" class="empty">No dispatch clients.</td></tr>';
    const lt=($('dispatchLoadSearch')?.value||'').toLowerCase(),sf=$('dispatchLoadStatus')?.value||'all';$('dispatchLoadRows').innerHTML=ls.filter(l=>(sf==='all'||l.status===sf)&&[l.load_number,l.origin,l.destination,l.broker_name].join(' ').toLowerCase().includes(lt)).map(l=>{const c=clients.find(c=>c.id===l.client_id),t=trucks.find(t=>t.id===l.truck_id),d=dispatchers.find(d=>d.id===l.dispatcher_id);return `<tr class="dispatch-load-view" data-id="${l.id}" style="cursor:pointer"><td><strong>${esc(l.load_number)}</strong><small>${esc(l.source_board||'')}</small></td><td>${esc(c?.company_name||'—')} / ${esc(t?.unit_number||'—')}</td><td>${esc(l.origin)} → ${esc(l.destination)}</td><td>${money(l.rate)}</td><td>${money(l.dispatch_fee)}</td><td>${esc(d?.full_name||'—')}</td><td><span class="dispatch-badge ${l.status==='delivered'||l.status==='paid'?'green':''}">${esc(l.status)}</span></td></tr>`}).join('')||'<tr><td colspan="7" class="empty">No accepted loads in this period.</td></tr>';
    $('dispatcherRows').innerHTML=dispatchers.map(d=>{const n=trucks.filter(t=>t.dispatcher_assignment_id&&assignments.some(a=>a.id===t.dispatcher_assignment_id&&a.dispatcher_id===d.id&&a.active)).length;return `<tr><td><strong>${esc(d.full_name)}</strong></td><td>${esc(d.email||'')}</td><td>${n}</td><td>${n}/5</td><td><span class="dispatch-badge ${d.is_active?'green':'amber'}">${d.is_active?'Active':'Inactive'}</span></td></tr>`}).join('')||'<tr><td colspan="5" class="empty">No dispatchers.</td></tr>';
  }
  function bind(){
    $('dispatchRefresh').onclick=loadAll;$('dispatchPeriod').onchange=render;$('dispatchClientSearch').oninput=render;$('dispatchLoadSearch').oninput=render;$('dispatchLoadStatus').onchange=render;
    document.querySelectorAll('.dispatch-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.dispatch-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');['dispatchClientsTab','dispatchLoadsTab','dispatchersTab'].forEach(id=>$(id).classList.add('hidden'));$(b.dataset.tab==='clients'?'dispatchClientsTab':b.dataset.tab==='loads'?'dispatchLoadsTab':'dispatchersTab').classList.remove('hidden')});
    $('newDispatchClient').onclick=()=>openClientModal();$('newDispatchLoad').onclick=()=>openLoadModal();$('newDispatcher').onclick=()=>{alert('Use the Create Dispatcher flow from the Dispatchers tab. The secure account creator is already installed; the profile form will be added next.')};
    document.addEventListener('click',e=>{const b=e.target.closest('.dispatch-client-view');if(b)openClientModal(b.dataset.id);const l=e.target.closest('.dispatch-load-view');if(l)openLoadModal(l.dataset.id)},false);
  }
  function modal(id,title,body){let m=$(id);if(!m){m=document.createElement('div');m.id=id;m.className='dispatch-modal hidden';document.body.appendChild(m)}m.innerHTML=`<div class="dispatch-backdrop"></div><section class="dispatch-dialog"><button class="dispatch-close">×</button><div class="kicker">DISPATCH</div><h3>${title}</h3>${body}</section>`;m.classList.remove('hidden');m.querySelector('.dispatch-close').onclick=()=>m.classList.add('hidden');m.querySelector('.dispatch-backdrop').onclick=()=>m.classList.add('hidden');return m}
  function openClientModal(id){const c=clients.find(x=>x.id===id);const ts=c?trucks.filter(t=>t.client_id===c.id):[];const as=c?assignments.filter(a=>a.client_id===c.id&&a.active):[];const body=`<form class="dispatch-form" id="clientForm"><label>Company Name<input id="dc_company" required value="${esc(c?.company_name||'')}"></label><label>Contact Name<input id="dc_contact" value="${esc(c?.contact_name||'')}"></label><label>Email<input id="dc_email" type="email" value="${esc(c?.email||'')}"></label><label>Phone<input id="dc_phone" value="${esc(c?.phone||'')}"></label><label>MC Number<input id="dc_mc" value="${esc(c?.mc_number||'')}"></label><label>DOT Number<input id="dc_dot" value="${esc(c?.dot_number||'')}"></label><label>Fee Type<select id="dc_fee"><option value="percentage">Percentage</option><option value="flat">Flat Per Load</option></select></label><label>Fee Value<input id="dc_feeval" type="number" step="0.01" value="${esc(c?.fee_value||'')}"></label><label>Status<select id="dc_status"><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label>Start Date<input id="dc_start" type="date" value="${esc(c?.start_date||'')}"></label><label class="full">Notes<textarea id="dc_notes">${esc(c?.notes||'')}</textarea></label><div class="full"><h4>Fleet (${ts.length})</h4><p class="panel-subtitle">Dispatcher capacity is limited to 5 active trucks per dispatcher.</p><div>${ts.map(t=>`<div style="padding:9px 0;border-bottom:1px solid #edf1f5"><strong>${esc(t.unit_number||'Truck')}</strong> · ${esc(t.equipment_type||'')} · ${esc(t.driver_name||'No driver')} <span class="dispatch-badge">${esc(t.status)}</span></div>`).join('')||'No trucks yet.'}</div></div><div class="full dispatch-actions"><button type="button" class="outline" id="addTruckFromClient">+ Add Truck</button><button type="submit" class="primary">${id?'Save Client':'Create Client'}</button></div></form>`;const m=modal('clientModal',id?'Manage Dispatch Client':'New Dispatch Client',body);$('dc_fee').value=c?.fee_type||'percentage';$('clientForm').onsubmit=async e=>{e.preventDefault();const payload={company_name:$('dc_company').value.trim(),contact_name:$('dc_contact').value.trim(),email:$('dc_email').value.trim(),phone:$('dc_phone').value.trim(),mc_number:$('dc_mc').value.trim(),dot_number:$('dc_dot').value.trim(),fee_type:$('dc_fee').value,fee_value:Number($('dc_feeval').value||0),status:$('dc_status').value,start_date:$('dc_start').value||null,notes:$('dc_notes').value.trim(),updated_at:new Date().toISOString()};const r=id?await db.from('dispatch_clients').update(payload).eq('id',id):await db.from('dispatch_clients').insert(payload);if(r.error){alert(r.error.message);return}m.classList.add('hidden');await loadAll()};$('addTruckFromClient').onclick=()=>{m.classList.add('hidden');openTruckModal(c?.id)} }
  function openTruckModal(clientId){const body=`<form class="dispatch-form" id="truckForm"><label>Client<select id="dt_client">${clients.map(c=>`<option value="${c.id}" ${c.id===clientId?'selected':''}>${esc(c.company_name)}</option>`).join('')}</select></label><label>Unit Number<input id="dt_unit" required></label><label>Equipment Type<input id="dt_equipment" placeholder="Dry Van / Reefer / Flatbed"></label><label>Truck Type<input id="dt_type" placeholder="Tractor / Straight Truck"></label><label>Year<input id="dt_year" type="number"></label><label>Make<input id="dt_make"></label><label>Model<input id="dt_model"></label><label>Driver Name<input id="dt_driver"></label><label>Driver Phone<input id="dt_phone"></label><label>Home City<input id="dt_city"></label><label>Home State<input id="dt_state" maxlength="2"></label><label>Status<select id="dt_status"><option value="active">Active</option><option value="inactive">Inactive</option><option value="maintenance">Maintenance</option></select></label><div class="full dispatch-actions"><button type="submit" class="primary">Save Truck</button></div></form>`;const m=modal('truckModal','Add Dispatch Truck',body);$('truckForm').onsubmit=async e=>{e.preventDefault();const r=await db.from('dispatch_trucks').insert({client_id:$('dt_client').value,unit_number:$('dt_unit').value.trim(),equipment_type:$('dt_equipment').value.trim(),truck_type:$('dt_type').value.trim(),year:Number($('dt_year').value||0)||null,make:$('dt_make').value.trim(),model:$('dt_model').value.trim(),driver_name:$('dt_driver').value.trim(),driver_phone:$('dt_phone').value.trim(),home_city:$('dt_city').value.trim(),home_state:$('dt_state').value.trim().toUpperCase(),status:$('dt_status').value});if(r.error){alert(r.error.message);return}m.classList.add('hidden');await loadAll()}}
  function openLoadModal(id){const l=loads.find(x=>x.id===id);const body=`<form class="dispatch-form" id="loadForm"><label>Client<select id="dl_client">${clients.map(c=>`<option value="${c.id}" ${c.id===l?.client_id?'selected':''}>${esc(c.company_name)}</option>`).join('')}</select></label><label>Truck<select id="dl_truck"></select></label><label>Dispatcher<select id="dl_disp">${dispatchers.map(d=>`<option value="${d.id}" ${d.id===l?.dispatcher_id?'selected':''}>${esc(d.full_name)}</option>`).join('')}</select></label><label>Source Board<select id="dl_board"><option>DAT</option><option>Truckstop</option><option>Other</option></select></label><label>Board Reference<input id="dl_ref" value="${esc(l?.board_reference||'')}"></label><label>Status<select id="dl_status"><option>accepted</option><option>booked</option><option>picked_up</option><option>in_transit</option><option>delivered</option><option>invoiced</option><option>paid</option></select></label><label>Origin<input id="dl_origin" required value="${esc(l?.origin||'')}"></label><label>Destination<input id="dl_dest" required value="${esc(l?.destination||'')}"></label><label>Pickup Date<input id="dl_pickup" type="date" value="${esc(l?.pickup_date||'')}"></label><label>Delivery Date<input id="dl_delivery" type="date" value="${esc(l?.delivery_date||'')}"></label><label>Equipment<input id="dl_equipment" value="${esc(l?.equipment||'')}"></label><label>Commodity<input id="dl_commodity" value="${esc(l?.commodity||'')}"></label><label>Miles<input id="dl_miles" type="number" step="0.1" value="${esc(l?.miles||'')}"></label><label>Accepted Rate<input id="dl_rate" type="number" step="0.01" required value="${esc(l?.rate||'')}"></label><label>Broker Name<input id="dl_broker" value="${esc(l?.broker_name||'')}"></label><label>Broker Phone<input id="dl_brokerphone" value="${esc(l?.broker_phone||'')}"></label><label>Broker Email<input id="dl_brokeremail" type="email" value="${esc(l?.broker_email||'')}"></label><label class="full">Notes<textarea id="dl_notes">${esc(l?.notes||'')}</textarea></label><div class="full"><div style="background:#f5f9fc;padding:14px;border-radius:12px"><strong>Dispatch fee: </strong><span id="dl_feePreview">—</span></div></div><div class="full dispatch-actions"><button type="submit" class="primary">${id?'Save Load':'Record Accepted Load'}</button></div></form>`;const m=modal('loadModal','Accepted Dispatch Load',body);function refreshTrucks(){const arr=trucks.filter(t=>t.client_id===$('dl_client').value&&t.status==='active');$('dl_truck').innerHTML=arr.map(t=>`<option value="${t.id}">${esc(t.unit_number)} — ${esc(t.driver_name||'No driver')}</option>`).join('')||'<option value="">No active trucks</option>';if(l?.truck_id)$('dl_truck').value=l.truck_id;}
    function fee(){const c=clients.find(x=>x.id===$('dl_client').value);const rate=Number($('dl_rate').value||0);let f=0;if(c?.fee_type==='percentage')f=rate*Number(c.fee_value||0)/100;else f=Number(c?.fee_value||0);$('dl_feePreview').textContent=money(f)}$('dl_client').onchange=()=>{refreshTrucks();fee()};$('dl_rate').oninput=fee;refreshTrucks();fee();$('loadForm').onsubmit=async e=>{e.preventDefault();const c=clients.find(x=>x.id===$('dl_client').value);const rate=Number($('dl_rate').value||0);const feeVal=c?.fee_type==='percentage'?rate*Number(c.fee_value||0)/100:Number(c?.fee_value||0);const payload={client_id:$('dl_client').value,truck_id:$('dl_truck').value||null,dispatcher_id:$('dl_disp').value||null,source_board:$('dl_board').value,board_reference:$('dl_ref').value.trim(),status:$('dl_status').value,origin:$('dl_origin').value.trim(),destination:$('dl_dest').value.trim(),pickup_date:$('dl_pickup').value||null,delivery_date:$('dl_delivery').value||null,equipment:$('dl_equipment').value.trim(),commodity:$('dl_commodity').value.trim(),miles:Number($('dl_miles').value||0)||null,rate,rate_per_mile:Number($('dl_miles').value)>0?rate/Number($('dl_miles').value):null,dispatch_fee:feeVal,notes:$('dl_notes').value.trim(),accepted_at:l?.accepted_at||new Date().toISOString(),updated_at:new Date().toISOString()};const r=id?await db.from('dispatch_loads').update(payload).eq('id',id):await db.from('dispatch_loads').insert(payload);if(r.error){alert(r.error.message);return}m.classList.add('hidden');await loadAll()}}

  async function init(){
    if(!db)return;try{const {data:{user}}=await db.auth.getUser();if(!user)return;const {data:p,error}=await db.from('employee_profiles').select('id,full_name,email,is_active,access_level,role').eq('id',user.id).maybeSingle();if(error||!p)return;profile=p;if(!['administrator','dispatcher'].includes(p.access_level))return;addNav();buildSection();await loadAll();}catch(e){console.error('Dispatch module failed',e)}
  }
  window.refreshMightDispatch=loadAll;
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else setTimeout(init,100);
})();
