const SUPABASE_URL='https://sowdiflodjxxqrarbisi.supabase.co';
const SUPABASE_KEY='sb_publishable_3URkcBfqIZmtujzRnO1a1g_Xdadmjvt';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);const $=id=>document.getElementById(id);let loads=[],currentUser=null,currentProfile=null;
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v||0).toLocaleString('en-US',{style:'currency',currency:'USD'});
const fmtDate=v=>{if(!v)return'—';const d=new Date(/^\d{4}-\d{2}-\d{2}$/.test(String(v))?`${v}T00:00:00`:v);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(d)};
const statusLabel=v=>String(v||'').replace(/_/g,' ');
async function profile(){const{data:{user},error}=await db.auth.getUser();if(error)throw error;if(!user)return null;const{data:p,error:pe}=await db.from('employee_profiles').select('id,full_name,email,access_level,is_active').eq('id',user.id).maybeSingle();if(pe)throw pe;return{user,profile:p}}
async function boot(){try{const r=await profile();if(!r){showLogin();return}currentUser=r.user;currentProfile=r.profile;if(!currentProfile||currentProfile.access_level!=='broker'||!currentProfile.is_active){$('loginError').textContent='This portal is restricted to active broker accounts.';await db.auth.signOut();showLogin();return}$('userName').textContent=currentProfile.full_name||currentUser.email||'Broker';$('loginView').classList.add('hidden');$('app').classList.remove('hidden');await loadLoads()}catch(e){console.error(e);$('loginError').textContent='Unable to load your broker profile. Please try again.';showLogin()}}
function showLogin(){$('app').classList.add('hidden');$('loginView').classList.remove('hidden')}
async function signIn(e){e.preventDefault();$('loginError').textContent='';const{error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error){$('loginError').textContent=error.message;return}await boot()}
async function loadLoads(){$('rows').innerHTML='<tr><td colspan="8" class="empty">Loading your loads…</td></tr>';const{data,error}=await db.from('loads').select('*').order('created_at',{ascending:false});if(error){$('rows').innerHTML=`<tr><td colspan="8" class="empty">Could not load your loads.<br><small>${esc(error.message)}</small></td></tr>`;return}loads=data||[];render();stats()}
function stats(){const active=loads.filter(l=>!['delivered','invoiced','paid','cancelled'].includes(l.status)).length;$('statActive').textContent=active;$('statBooked').textContent=loads.filter(l=>l.status==='booked').length;$('statTransit').textContent=loads.filter(l=>['dispatched','picked_up','in_transit'].includes(l.status)).length;$('statDelivered').textContent=loads.filter(l=>['delivered','invoiced','paid'].includes(l.status)).length}
function render(){const term=$('search').value.trim().toLowerCase(),filter=$('status').value;const filtered=loads.filter(l=>{if(filter!=='all'&&l.status!==filter)return false;if(!term)return true;return[l.load_number,l.origin,l.destination,l.equipment,l.carrier_name,l.carrier_mc,l.driver_name].some(v=>String(v||'').toLowerCase().includes(term))});if(!filtered.length){$('rows').innerHTML='<tr><td colspan="8" class="empty">No loads match your filters.</td></tr>';return}$('rows').innerHTML=filtered.map(l=>`<tr><td><strong>${esc(l.load_number)}</strong><span class="sub">Created ${fmtDate(l.created_at)}</span></td><td class="lane">${esc(l.origin)}<span>→</span>${esc(l.destination)}</td><td>${fmtDate(l.pickup_date)}</td><td>${esc(l.equipment||'—')}</td><td>${esc(l.carrier_name||'Unassigned')}<span class="sub">${esc(l.carrier_mc||'')}</span></td><td><span class="status">${esc(statusLabel(l.status))}</span></td><td>${l.customer_rate!=null?money(l.customer_rate):'—'}</td><td><button class="outline view" data-id="${esc(l.id)}">View</button></td></tr>`).join('');document.querySelectorAll('.view').forEach(b=>b.addEventListener('click',()=>openLoad(b.dataset.id)))}
function detail(label,value,full=false){return`<div class="detail ${full?'full':''}"><span>${label}</span><strong>${value||'—'}</strong></div>`}
function openLoad(id){const l=loads.find(x=>String(x.id)===String(id));if(!l)return;$('drawerTitle').textContent=l.load_number;$('drawerBody').innerHTML=`<div class="notice">This record is visible because it is assigned to your broker account. Other brokers cannot retrieve it through the database.</div><div class="grid">${detail('Origin',esc(l.origin))}${detail('Destination',esc(l.destination))}${detail('Pickup',fmtDate(l.pickup_date))}${detail('Delivery',fmtDate(l.delivery_date))}${detail('Equipment',esc(l.equipment))}${detail('Commodity',esc(l.commodity))}${detail('Weight',l.weight?`${Number(l.weight).toLocaleString('en-US')} lbs`:'—')}${detail('Status',`<span class="status">${esc(statusLabel(l.status))}</span>`)}${detail('Customer Rate',l.customer_rate!=null?money(l.customer_rate):'—')}${detail('Carrier Rate',l.carrier_rate!=null?money(l.carrier_rate):'—')}${detail('Gross Margin',l.gross_margin!=null?money(l.gross_margin):'—')}${detail('Carrier',esc(l.carrier_name))}${detail('MC',esc(l.carrier_mc))}${detail('Driver',esc(l.driver_name))}${detail('Driver Phone',esc(l.driver_phone))}${detail('Truck #',esc(l.truck_number))}${detail('Trailer #',esc(l.trailer_number))}${detail('Pickup Window',esc([l.pickup_time_from,l.pickup_time_to].filter(Boolean).join(' – ')))}${detail('Delivery Window',esc([l.delivery_time_from,l.delivery_time_to].filter(Boolean).join(' – ')))}${detail('Special Requirements',esc(l.special_requirements),true)}${detail('Driver Instructions',esc(l.driver_instructions),true)}</div>`;$('drawer').classList.remove('hidden')}
function closeDrawer(){$('drawer').classList.add('hidden')}
$('loginForm').addEventListener('submit',signIn);$('signOut').addEventListener('click',async()=>{await db.auth.signOut();showLogin()});$('refresh').addEventListener('click',loadLoads);$('search').addEventListener('input',render);$('status').addEventListener('change',render);$('close').addEventListener('click',closeDrawer);$('backdrop').addEventListener('click',closeDrawer);db.auth.onAuthStateChange(e=>{if(e==='SIGNED_OUT')showLogin()});boot();
